### ISSUE TITLE
1-1-1-1 Priority fixes while CD is away...

### ISSUE THREAD

**Issue by carldavaz** [registerguard/bulldog#75]
- [x] Implement Go widget #63 
- [x] Fix FaceBook sharing/picture issue
- [x] Implement "Email this story" https://github.com/registerguard/tracker/issues/14
- [x] Implement "Print this story" https://github.com/registerguard/tracker/issues/15
- [ ] Bob Welch logo https://github.com/registerguard/tracker/issues/39
- [ ] Add related items to summary templates https://github.com/registerguard/tracker/issues/44
